apiVersion: v1
kind: Service
metadata:
  name: { { include "compiler.fullname" . } }
  labels:
    { { - include "compiler.labels" . | nindent 4 } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    { { - include "compiler.selectorLabels" . | nindent 4 } }
